dist: trusty
sudo: required

notifications:
  email:
    - 00hnes@gmail.com

language: c

compiler:
  - gcc
  - clang

install:
    - sudo apt-get install -qq -y libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl make build-essential valgrind gcc-multilib g++-multilib libc6-dbg libc6-dbg:i386
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-key update
    
script:
    - echo $TRAVIS_EVENT_TYPE
    - ulimit -c unlimited
    - cat /proc/cpuinfo && free -m && uname -a
    - cc --version
    - gcc --version
    - echo $CC
    - ls /usr/include
    - ls /usr/include/valgrind
    - date
    - mkdir output
    - bash make.sh
    - ls output
    - ls output | wc -l
    - cd output
    - bash ../test.sh
    - cd ..
    - rm -fr output
    - mkdir output
    - bash make.sh -o no-m32
    - ls output
    - ls output | wc -l
    - cd output
    - bash ../test.sh
    - cd ..
    - rm -fr output
    - mkdir output
    - bash make.sh -o no-valgrind
    - ls output
    - ls output | wc -l
    - cd output
    - bash ../test.sh
    - cd ..
    - rm -fr output
    - mkdir output
    - bash make.sh -o no-valgrind -o no-m32
    - ls output
    - ls output | wc -l
    - cd output
    - bash ../test.sh
    - cd ..
    - rm -fr output
